### ISSUE TITLE
Add ".idea" folder to .gitignore and/or .npmignore

### ISSUE THREAD

**Issue by pdehaan** [vladikoff/fxa-conventional-changelog#1]
I was just poking around my node_modules folder and noticed that after installing this module via npm, it comes with a free ".idea" folder, which I think comes from intellij, or something. Probably unnecessary.
### STR

``` sh
$ npm init --yes
$ npm i fxa-conventional-changelog -D
$ ls -lh node_modules/fxa-conventional-changelog

-rw-r--r--  1 pdehaan  staff   189B Sep 11 08:12 README.md
-rw-r--r--  1 pdehaan  staff   2.2K Sep 11 08:10 index.js
drwxr-xr-x  7 pdehaan  staff   238B Jan 12 12:55 node_modules
-rw-r--r--  1 pdehaan  staff   1.2K Jan 12 12:55 package.json
drwxr-xr-x  6 pdehaan  staff   204B Jan 12 12:55 templates
drwxr-xr-x  3 pdehaan  staff   102B Sep 11 07:58 tests
```

Not sure if we also want to add "tests/" to .npmignore since those wouldn't really be needed by somebody using the module, although I guess this module would only be used in dev and not prod, so who cares.

**Comment by vladikoff** [comment]
@pdehaan wacky!
